services:
  storage:
    image: oittaa/gcp-storage-emulator
    environment:
      - PORT=9023
    ports:
      - 9023:9023
    volumes:
      - ./devtools/gcp-storage-emulator/data:/storage
    container_name: storage-sds-loader
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - STORAGE_EMULATOR_HOST=http://storage:9023
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - PUBSUB_EMULATOR_HOST=firestore:8085
      - FIRESTORE_PROJECT_ID=mock-project-id
      - PUBSUB_PROJECT_ID=mock-project-id
      - LOG_LEVEL=DEBUG
      - PROJECT_ID=mock-project-id
    restart: on-failure
    depends_on:
      - firestore
      - storage
    container_name: sds-loader-app
  firestore:
    image: spine3/firebase-emulator
    ports:
      - 8080:8080
      - 4001:4001
      - 8085:8085
    environment:
      - GCP_PROJECT=mock-project-id
      - ENABLE_UI=true
    volumes:
      - ./devtools/firebase-emulator:/firebase
      - ./devtools/firebase-emulator:/firebase/baseline-data
    container_name: sds-loader-firestore
